# Testing Netlify Builds

#SSG
#serverful or SSG next.js settings SSG is just exported
# public folder needs to be empty of public/_next/ and public/_redirects file
[build]
  command = "npm run deploy"
  publish = "out"

[dev]
  functions = "functions"
  publish = "out"


# use `npm run serve` to serve up static only


# [build_serverless]
# #serverless next.js settings

# [build]
#   command   = "npm run serverless"
#   functions = "functions"
#   publish   = "public"

# [dev]
#   command   = "npx serve public -p 3000"
#   functions = "functions"
#   publish = "public"


  
[[plugins]]
package = "netlify-plugin-cache-nextjs"