[build]
  command   = "npm run deploy"
  functions = "functions"
  publish   = "out"

[dev]
  functions = "functions"
  publish = "out"
  framework= "#static"
  # command   = "npx serve ./public -p 3000"
  # command = "npm run dev"
  # command = "echo no dev command executing..."
  
[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-From = "netlify.toml"
  